services:

  backend:
    image: piyushsingh19/lostfound-backend:latest
    container_name: lostfound_backend_prod

    ports:
      - "5002:5002"

    env_file:
      - ./backend/.env

    environment:
      - NODE_ENV=production
      - PORT=5002

    restart: always

    networks:
      - mern_network

  frontend:
    image: piyushsingh19/lostfound-frontend:latest
    container_name: lostfound_frontend_prod

    ports:
      - "5173:5173"

    env_file:
      - ./frontend/.env

    restart: always

    depends_on:
      - backend

    networks:
      - mern_network

networks:
  mern_network:
    driver: bridge